import 'models.dart';

/// Bundled sample documents, taken from the two reference scans. Used as the
/// OCR fallback so the demo always has something to show, and to seed the
/// farmer directory on first launch.

Patta samplePatta() => Patta(
      pattaNumber: '10337',
      surveyNumber: '490',
      subDivision: '4B',
      landType: 'புன்செய் (Dry)',
      extent: '0 - 87.00',
      extentUnit: 'Hectares - Ares',
      waterRate: '2.00',
      district: 'தென்காசி',
      taluk: 'கடையநல்லூர்',
      village: 'சொக்கம்பட்டி',
      ownerName: 'ராமசாமி',
      remarks: '-',
      mocked: true,
    );

Certificate sampleCertificate() => Certificate(
      certNo: 'TN-920260804671',
      certDate: '10-08-2026',
      farmerName: 'Thiru Ayyakutty',
      fatherName: 'Thiru Krishnan',
      address: 'Door No. 1/400, Avudaiyamman temple street, Tharuval',
      district: 'Tirunelveli',
      taluk: 'Palayamkottai',
      village: 'Tharuval',
      totalExtentAcres: 1.5073,
      rows: [
        LandRow(district: 'Tirunelveli', taluk: 'Palayamkottai', village: 'Tharuval', pattaNo: '2719', surveyNo: '230/3', landType: 'நன்செய்', extentAcres: 0.4448),
        LandRow(district: 'Tirunelveli', taluk: 'Palayamkottai', village: 'Tharuval', pattaNo: '4163', surveyNo: '229/1', landType: 'நன்செய்', extentAcres: 0.2718),
        LandRow(district: 'Tirunelveli', taluk: 'Palayamkottai', village: 'Tharuval', pattaNo: '3497', surveyNo: '233', landType: 'நன்செய்', extentAcres: 0.7907),
      ],
      mocked: true,
    );

Patta _acrePatta(String patta, String survey, String sub, String extent, String village, String taluk, {String owner = ''}) => Patta(
      pattaNumber: patta,
      surveyNumber: survey,
      subDivision: sub,
      landType: 'நன்செய் (Wet)',
      extent: extent,
      extentUnit: 'Acres',
      district: 'Tirunelveli',
      taluk: taluk,
      village: village,
      ownerName: owner,
    );

List<Farmer> seedFarmers() => [
      // Matches sampleCertificate() exactly - the happy path of the demo.
      Farmer(
        id: 'L-2026-0911-002',
        stage: LeadStage.verified,
        createdAt: DateTime(2026, 9, 11, 16, 18),
        fields: {
          'name': 'Thiru Ayyakutty',
          'fatherName': 'Thiru Krishnan',
          'mobile': '+91 98765 11902',
          'aadhaar': '4412 9087 3311',
          'address': 'Door No. 1/400, Avudaiyamman temple street, Tharuval',
          'gender': 'Male',
          'community': 'General',
          'state': 'Tamil Nadu',
          'district': 'Tirunelveli',
          'taluk': 'Palayamkottai',
          'village': 'Tharuval',
          'landExtent': '1.5073',
          'landUnit': 'Acres',
          'landOwnership': 'Own',
          'productCategory': 'Agri Equipment',
          'productName': 'Power Weeder (Sarathy i06)',
          'brand': 'Sarathy',
          'price': '85,000',
          'scheme': 'Subsidy',
          'subsidyPercent': '50%',
        },
        pattas: [
          _acrePatta('2719', '230', '3', '0.4448', 'Tharuval', 'Palayamkottai', owner: 'Thiru Ayyakutty'),
          _acrePatta('4163', '229', '1', '0.2718', 'Tharuval', 'Palayamkottai', owner: 'Thiru Ayyakutty'),
          _acrePatta('3497', '233', '', '0.7907', 'Tharuval', 'Palayamkottai', owner: 'Thiru Ayyakutty'),
        ],
      ),
      Farmer(
        id: 'L-2026-0911-001',
        stage: LeadStage.confirmed,
        createdAt: DateTime(2026, 9, 11, 10, 0),
        fields: {
          'name': 'Ramesh Kumar',
          'fatherName': 'Muthusamy',
          'mobile': '+91 98765 43210',
          'aadhaar': '1234 5678 9012',
          'address': 'Nanguneri, Tirunelveli - 627108',
          'gender': 'Male',
          'community': 'SC',
          'state': 'Tamil Nadu',
          'district': 'Tirunelveli',
          'taluk': 'Nanguneri',
          'village': 'Nanguneri',
          'landExtent': '2.50',
          'landUnit': 'Acres',
          'landOwnership': 'Own',
          'productCategory': 'Agri Equipment',
          'productName': 'Power Weeder (Sarathy i06)',
          'brand': 'Sarathy',
          'price': '85,000',
          'scheme': 'Subsidy',
          'subsidyPercent': '50%',
        },
        pattas: [_acrePatta('1234', '56', '1A', '2.50', 'Nanguneri', 'Nanguneri', owner: 'Ramesh Kumar')],
      ),
      Farmer(
        id: 'L-2026-0910-004',
        stage: LeadStage.documents,
        createdAt: DateTime(2026, 9, 10, 11, 2),
        fields: {
          'name': 'Meena Selvi',
          'fatherName': 'Arumugam',
          'mobile': '+91 90032 45518',
          'state': 'Tamil Nadu',
          'district': 'Tirunelveli',
          'taluk': 'Palayamkottai',
          'village': 'Palayamkottai',
          'landExtent': '1.10',
          'landUnit': 'Acres',
          'landOwnership': 'Lease',
          'productCategory': 'Irrigation',
          'productName': 'Drip Irrigation Kit',
        },
        pattas: [_acrePatta('8842', '112', '2', '1.10', 'Palayamkottai', 'Palayamkottai', owner: 'Meena Selvi')],
      ),
      Farmer(
        id: 'L-2026-0908-007',
        stage: LeadStage.delivered,
        createdAt: DateTime(2026, 9, 8, 9, 30),
        fields: {
          'name': 'Arumugam S',
          'fatherName': 'Sankaran',
          'mobile': '+91 94422 71190',
          'state': 'Tamil Nadu',
          'district': 'Thoothukudi',
          'taluk': 'Srivaikuntam',
          'village': 'Kurumbur',
          'landExtent': '4.20',
          'landUnit': 'Acres',
          'landOwnership': 'Own',
          'productCategory': 'Tractor',
          'productName': 'Mini Tractor 22HP',
          'brand': 'Sonalika',
          'price': '4,25,000',
          'scheme': 'Non-Subsidy',
        },
        pattas: [_acrePatta('4501', '88', '3C', '4.20', 'Kurumbur', 'Srivaikuntam', owner: 'Arumugam S')],
      ),
    ];
